language: r
sudo: required
cache: packages
r:
  - release

services:
  - xvfb

r_packages:
  - devtools
  - covr

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: false

after_success:
  - Rscript -e 'library(covr); codecov()'
  
